[package]
name = "discord-rpc-video-player"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
discord-rpc-client = "0.3.0"
#tray-item = "0.7.0"
#tokio = { version = "1.17.0", features = ["full"] }